# Generated by Django 4.1 on 2023-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xhatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savequeries",
            name="query_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
